services:


  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: smart-building-client
    container_name: SmartBuildingClient
    restart: unless-stopped
    ports:
      - 54085:80